ARG PYTHON_VERSION=3.11.1
FROM python:${PYTHON_VERSION}-slim

RUN pip install --upgrade pip setuptools \
    && pip install \
        docutils \
        flake8 \
        isort \
        mypy \
        pydocstyle \
        tox \
    && mypy --install-types --non-interactive -c 'import requests'
