name: Update release version
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.2.0

      - name: Perform lint
        run: make lint

      - name: Perform tests
        run: make test

      - name: Perform dist
        run: make dist

      - name: Test pip package installation.
        run: make installcheck

      - name: Add GitHub tag and release
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
